### ISSUE TITLE
Downloader keeps logging in

### ISSUE THREAD

**Issue by GibzonDev** [Austio/ruby-tapas-downloader#6]
When using all the default options and Chromedriver, I keep getting to the login page for each episode. Could this be a bug, because considering there's a method called login_if_needed check, I guess this is not how it should work?
Can you really close the browser after each download as it does now? Isn't the session cleared then?

To fix this problem for me, I changed the code so that the browser is instead created in the main class and passed along to first episode_links and then to episode_page. And removed "browser.close" after the download. Everything now works as expected. If you find it useful I can commit to a branch if you let me.

**Comment by Austio** [comment]
Thanks for the message, this was by habit from building other scrapers.  I generally setup/teardown at each step.  

Is definitely more efficient to do it the way you say though.  Feel free to create a PR if you think it is valuable.

**Comment by GibzonDev** [comment]
Yeah I can definitely see a benefit in that. 
In this particular case though it's probably best to stay logged in to not bother Ruby tapas too much :)
PR created!
