### ISSUE TITLE
Does not navigate to rubytapas.com

### ISSUE THREAD

**Issue by fanaugen** [Austio/ruby-tapas-downloader#9]
I installed the `watir` and `selenium-webdriver` gems and put the `chromedriver` executable in my PATH.

Now when running the downloader, I get a deprecation warning for `watir`, the browser opens an empty window with "`data:,`" in the location bar, and times our with `EOFError` after a few seconds. 

Any ideas?

[edit] changing the [1st line](https://github.com/Austio/ruby-tapas-downloader/blob/master/ruby-tapas-downloader.rb#L1) to `require "watir"` gets rid of the warning, but the issue persists

![screenshot](http://i.imgur.com/QtcgvAv.png)

**Comment by Austio** [comment]
@fanaugen thanks for letting everyone know.  I just ran on win10 with chrome and saw similar.  Switching to firefox will allow it to work.

This is probably due to an update on chrome that stopped supporting some api that watir is using.  Feel free to submit a PR if you want to fix it.
